#!/bin/bash
# USAGE
#     BasinComps (-tinFileList file | (-tinFile fileSpec...) (-tinPath pathSpec...))
#         (-basinFileList file | (-basinFile fileSpec...))
#         [-sTime time] [-dTime timespan] [-eTime time] [-tinInputInterval timeInterval]
#         [-instantaneousInput] [-readTimeZone timeZone] [-bPartColumn columnName]
#         [-polyline] [-center centerpoint] [-move moveArg] [-gridCell | -TINSurface
#         [-shiftInTime timespan] [-zone] [-SI | -EN] [-writeTimeZone timeZone]
#         [-outputUnits units] [-cPart cPathPart] [-timeSeriesOutputInterval timeInterval]
#         [-instantaneousOutput] [-saveType saveType] [-outputFormat format]
#         [-textOutFile file] [-dssOutFile file] [-test] [-verbose]

$METVUE_EXE/utilities/unix/BasinComps \
 -tinFile  ./InputData/xmrg0613201015z \
 -basinFile ./InputData/shp/AmericanRiver.shp \
 -cPart precip \
 -dssOutFile ./OutputData/BasinComps.dss \
 -textOutFile ./OutputData/BasinComps.txt
 
 